services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: envelope-mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: envelope-app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /app/node_modules
      - ./db:/db
